[package]
name = "dramax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustx7 = { path = "F:/Coding/Github/RustX7/"}
colored = "2.0.4"
